In [1]:
from scipy.stats import ks_2samp

In [8]:
import numpy as np 
d1 = np.arange(10)
d2 = np.arange(100)
d3=np.arange(10)

In [3]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
d3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
test1=ks_2samp(d1 ,d2)
test1

KstestResult(statistic=np.float64(0.9), pvalue=np.float64(7.88295587183084e-09), statistic_location=np.int64(9), statistic_sign=np.int8(1))

In [12]:
test=ks_2samp(d1 ,d3)

In [13]:
test

KstestResult(statistic=np.float64(0.0), pvalue=np.float64(1.0), statistic_location=np.int64(0), statistic_sign=np.int8(1))

In [14]:
!pip install pyyaml



Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\shrav\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [18]:
from sensor.utils.main_utils import read_yaml_file

ImportError: cannot import name 'read_yaml_file' from 'sensor.utils.main_utils' (c:\Users\shrav\Desktop\Sensor Fault Detection\sensor\utils\main_utils.py)

In [16]:
!pip install dill

Defaulting to user installation because normal site-packages is not writeable
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Using cached dill-0.4.0-py3-none-any.whl (119 kB)



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\shrav\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
